"use client";

import { useMemo, useState } from "react";
import { buildWhatsAppUrl } from "@/lib/settings/whatsapp";
import { reservationStatuses, type ReservationInput, type ReservationStatus } from "@/lib/reservations/validation";

export type ReservationRecord = ReservationInput & { id: string; status: ReservationStatus; created_at: string; updated_at: string };

export function ReservationsManager({ initialReservations, whatsappNumber }: { initialReservations: ReservationRecord[]; whatsappNumber?: string }) {
  const [items, setItems] = useState(initialReservations);
  const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [date, setDate] = useState(""); const [ascending, setAscending] = useState(true);
  const [selected, setSelected] = useState<ReservationRecord | null>(null); const [feedback, setFeedback] = useState<string | null>(null);
  const visible = useMemo(() => items.filter((item) => (!search || `${item.name} ${item.phone}`.toLowerCase().includes(search.toLowerCase())) && (!status || item.status === status) && (!date || item.reservation_date === date)).sort((a,b) => `${a.reservation_date}${a.reservation_time ?? ""}`.localeCompare(`${b.reservation_date}${b.reservation_time ?? ""}`) * (ascending ? 1 : -1)), [items, search, status, date, ascending]);

  async function updateStatus(item: ReservationRecord, next: ReservationStatus) {
    setFeedback(null);
    const response = await fetch(`/api/admin/reservations/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: next }) });
    const body = await response.json() as { error?: string; reservation?: ReservationRecord };
    if (!response.ok || !body.reservation) { setFeedback(body.error ?? "Update failed."); return; }
    setItems((current) => current.map((record) => record.id === item.id ? body.reservation! : record)); setSelected(body.reservation); setFeedback("Status updated.");
  }
  const control = "min-h-11 rounded-md border border-dark-green/20 bg-white px-3 text-sm";
  return <section aria-labelledby="reservations-heading"><p className="text-xs font-semibold tracking-[0.2em] text-palem-green uppercase">Operations</p><h1 id="reservations-heading" className="mt-3 font-serif text-4xl sm:text-5xl">Reservations</h1>
    <div className="mt-8 grid gap-3 rounded-lg border border-dark-green/10 bg-white p-4 md:grid-cols-4"><label className="text-xs font-bold">Search<input value={search} onChange={(e)=>setSearch(e.target.value)} className={`${control} mt-2 w-full`} placeholder="Name or phone" /></label><label className="text-xs font-bold">Status<select value={status} onChange={(e)=>setStatus(e.target.value)} className={`${control} mt-2 w-full`}><option value="">All</option>{reservationStatuses.map((s)=><option key={s}>{s}</option>)}</select></label><label className="text-xs font-bold">Date<input type="date" value={date} onChange={(e)=>setDate(e.target.value)} className={`${control} mt-2 w-full`} /></label><button onClick={()=>setAscending((v)=>!v)} className={`${control} self-end font-semibold`}>Sort {ascending ? "earliest" : "latest"}</button></div>
    {feedback && <p role="status" className="mt-4 rounded-md border border-gold/30 bg-white p-3 text-sm">{feedback}</p>}
    <div className="mt-6 overflow-x-auto rounded-lg border border-dark-green/10 bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-dark-green text-white"><tr><th className="p-4">Guest</th><th className="p-4">Date / time</th><th className="p-4">Guests</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{visible.map((item)=><tr key={item.id} className="border-t border-dark-green/10"><td className="p-4"><span className="font-semibold">{item.name}</span><span className="block text-xs text-dark-green/55">{item.phone}</span></td><td className="p-4">{item.reservation_date}<span className="block text-xs text-dark-green/55">{item.reservation_time || "Time not specified"}</span></td><td className="p-4">{item.guest_count}</td><td className="p-4 capitalize">{item.status}</td><td className="p-4"><button className="font-bold text-palem-green underline-offset-4 hover:underline" onClick={()=>setSelected(item)}>View details</button></td></tr>)}</tbody></table>{!visible.length && <p className="p-8 text-center text-dark-green/55">No reservations match these filters.</p>}</div>
    {selected && <div role="dialog" aria-modal="true" aria-labelledby="reservation-detail" className="fixed inset-0 z-50 grid place-items-center bg-dark-green/70 p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-cream p-6 shadow-2xl sm:p-8"><div className="flex justify-between gap-4"><h2 id="reservation-detail" className="font-serif text-3xl">Reservation details</h2><button onClick={()=>setSelected(null)} aria-label="Close reservation details" className="h-10 w-10 rounded-full border border-dark-green/20">×</button></div><dl className="mt-6 grid gap-4 sm:grid-cols-2">{[["Name",selected.name],["Phone",selected.phone],["Date",selected.reservation_date],["Time",selected.reservation_time || "Not specified"],["Guests",String(selected.guest_count)],["Status",selected.status],["Created",new Date(selected.created_at).toLocaleString()],["Updated",new Date(selected.updated_at).toLocaleString()]].map(([label,value])=><div key={label}><dt className="text-xs font-bold tracking-wide uppercase text-dark-green/50">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>)}</dl><div className="mt-5"><h3 className="text-xs font-bold tracking-wide uppercase text-dark-green/50">Notes</h3><p className="mt-2 whitespace-pre-wrap">{selected.notes || "No notes provided."}</p></div><label className="mt-6 block text-sm font-bold">Update status<select value={selected.status} onChange={(e)=>void updateStatus(selected,e.target.value as ReservationStatus)} className={`${control} mt-2 w-full`}>{reservationStatuses.map((s)=><option key={s}>{s}</option>)}</select></label>{buildWhatsAppUrl(whatsappNumber,selected) && <a className="mt-5 inline-flex min-h-11 items-center rounded-full bg-palem-green px-5 text-xs font-bold tracking-wide text-white uppercase" target="_blank" rel="noreferrer" href={buildWhatsAppUrl(whatsappNumber,selected)!}>Contact via WhatsApp</a>}</div></div>}
  </section>;
}
