"use client";

import { useEffect, useState, type FormEvent } from "react";
import { settingDefinitions, settingGroups } from "@/lib/settings/config";

type MediaOption = { id: string; file_name: string };
export function SettingsManager({ initialValues, media, editable }: { initialValues: Record<string,string>; media: MediaOption[]; editable: boolean }) {
  const [values,setValues]=useState<Record<string,string|boolean>>(()=>Object.fromEntries(settingDefinitions.map((d)=>[d.key,d.kind==="boolean" ? initialValues[d.key] === "true" : initialValues[d.key] ?? ""]))); const [dirty,setDirty]=useState(false); const [pending,setPending]=useState(false); const [feedback,setFeedback]=useState<string|null>(null);
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty)e.preventDefault()};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
  async function save(e:FormEvent){e.preventDefault();setPending(true);setFeedback(null);const response=await fetch("/api/admin/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const body=await response.json() as {error?:string};setPending(false);if(!response.ok){setFeedback(body.error??"Settings could not be saved.");return}setDirty(false);setFeedback("Settings saved.")}
  const inputClass="mt-2 min-h-11 w-full rounded-md border border-dark-green/20 bg-white px-3 py-2 text-sm disabled:bg-dark-green/5";
  return <form onSubmit={save} onChange={()=>setDirty(true)}><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold tracking-[0.2em] text-palem-green uppercase">Configuration</p><h1 className="mt-3 font-serif text-4xl sm:text-5xl">Website settings</h1></div>{editable&&<button disabled={pending||!dirty} className="min-h-11 rounded-full bg-palem-green px-6 text-xs font-bold tracking-wide text-white uppercase disabled:opacity-45">{pending?"Saving…":"Save settings"}</button>}</div>{!editable&&<p className="mt-5 rounded-md border border-gold/40 bg-white p-4">Settings are read-only for your role.</p>}{feedback&&<p role="status" className="mt-5 rounded-md border border-gold/30 bg-white p-4">{feedback}</p>}<div className="mt-8 grid gap-6 xl:grid-cols-2">{settingGroups.map((group)=><fieldset key={group.key} disabled={!editable} className="rounded-xl border border-dark-green/10 bg-white p-5 sm:p-6"><legend className="px-2 font-serif text-2xl font-semibold">{group.label}</legend><div className="mt-3 grid gap-5">{settingDefinitions.filter((d)=>d.group===group.key).map((d)=><label key={d.key} className="text-sm font-semibold">{d.label}{d.description&&<span className="mt-1 block text-xs font-normal leading-5 text-dark-green/55">{d.description}</span>}{d.kind==="boolean"?<input type="checkbox" checked={Boolean(values[d.key])} onChange={(e)=>{setValues(v=>({...v,[d.key]:e.target.checked}));setDirty(true)}} className="ml-3 h-5 w-5 align-middle" />:d.kind==="media"?<select className={inputClass} value={String(values[d.key])} onChange={(e)=>setValues(v=>({...v,[d.key]:e.target.value}))}><option value="">Not configured</option>{media.map((m)=><option value={m.id} key={m.id}>{m.file_name}</option>)}</select>:d.kind==="textarea"||d.kind==="hours"?<textarea className={`${inputClass} min-h-28 resize-y font-${d.kind==="hours"?"mono":"sans"}`} value={String(values[d.key])} onChange={(e)=>setValues(v=>({...v,[d.key]:e.target.value}))} />:<input className={inputClass} type={d.kind==="email"?"email":d.kind==="number"?"number":"text"} value={String(values[d.key])} onChange={(e)=>setValues(v=>({...v,[d.key]:e.target.value}))} />}</label>)}</div></fieldset>)}</div></form>;
}
