import type { ReactNode } from "react";
import { notFound, redirect } from "next/navigation";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";
import { CollectionPage } from "@/components/public/collection-page";
import { MenuPresentation } from "@/components/public/menu-presentation";
import { Hero } from "@/components/sections/hero";
import { FeaturedExperience } from "@/components/sections/featured-experience";
import { Intro } from "@/components/sections/intro";
import { MenuCta } from "@/components/sections/menu-cta";
import { Venue } from "@/components/sections/venue";
import { UpdatesPreview } from "@/components/sections/updates-preview";
import { ReservationCta } from "@/components/sections/reservation-cta";
import { Location } from "@/components/sections/location";
import { getAdminUser } from "@/lib/auth/admin";
import { cmsModules, isCmsModuleKey } from "@/lib/cms/config";
import type { HomepageSectionContent } from "@/lib/public-content";
import { createClient } from "@/lib/supabase/server";

export const dynamic="force-dynamic";
type RecordRow=Record<string,unknown>;
export default async function PreviewPage({params,searchParams}:{params:Promise<{module:string;id:string}>;searchParams:Promise<{revision?:string}>}){const {module,id}=await params;const {revision}=await searchParams;if(!isCmsModuleKey(module))notFound();const user=await getAdminUser();if(!user)redirect("/login");if(user.role==="reservation_staff")return <PreviewError>Preview authorization denied.</PreviewError>;const config=cmsModules[module];const supabase=await createClient();const {data:current}=await supabase.from(config.table).select("*").eq("id",id).maybeSingle();if(!current)notFound();let selected:RecordRow=current;if(revision){const {data:historical}=await supabase.from("content_revisions").select("snapshot").eq("id",revision).eq("entity_type",config.table).eq("entity_id",id).maybeSingle();if(!historical)return <PreviewError>Revision preview is unavailable.</PreviewError>;selected={...current,...historical.snapshot};}
const attach=async(rows:RecordRow[])=>{const mediaIds=rows.map((row)=>String(row.media_id||row.image_media_id||"")).filter(Boolean);if(!mediaIds.length)return rows;const {data:media}=await supabase.from("media").select("id,storage_path,alt_text,title").in("id",mediaIds);const signed=media?.length?await supabase.storage.from("media").createSignedUrls(media.map((item)=>item.storage_path),600):{data:[]};const urls=new Map((signed.data??[]).map((item)=>[item.path,item.signedUrl]));return rows.map((row)=>{const match=media?.find((item)=>item.id===(row.media_id||row.image_media_id));return {...row,image_url:match?urls.get(match.storage_path)??null:null,image_alt:match?.alt_text||match?.title||null}})};
let content:ReactNode;if(module==="homepage-content"||module==="homepage-experiences"){const [sectionsResult,experiencesResult]=await Promise.all([supabase.from("homepage_content").select("*").order("created_at"),supabase.from("homepage_experiences").select("*").order("display_order")]);let sections=(sectionsResult.data??[]) as RecordRow[];let experiences=(experiencesResult.data??[]) as RecordRow[];if(module==="homepage-content")sections=sections.map((row)=>row.id===id?selected:row);else experiences=experiences.map((row)=>row.id===id?selected:row);sections=await attach(sections);experiences=await attach(experiences);const sectionMap=new Map(sections.map((row)=>[String(row.section_key),row as HomepageSectionContent]));content=<><Navbar mode="overlay"/><main><Hero content={sectionMap.get("hero")}/><Intro content={sectionMap.get("introduction")}/><FeaturedExperience experiences={experiences as never}/><MenuCta content={sectionMap.get("menu_cta")}/><Venue content={sectionMap.get("venue")}/><UpdatesPreview/><ReservationCta content={sectionMap.get("reservation_cta")}/><Location content={sectionMap.get("location")}/></main><Footer/></>;}else if(module==="menu-items"||module==="menu-categories"){const [categoriesResult,itemsResult]=await Promise.all([supabase.from("menu_categories").select("*").order("display_order"),supabase.from("menu_items").select("*").order("display_order")]);let categories=(categoriesResult.data??[]) as RecordRow[];let items=(itemsResult.data??[]) as RecordRow[];if(module==="menu-categories")categories=categories.map((row)=>row.id===id?selected:row);else items=items.map((row)=>row.id===id?selected:row);items=await attach(items);content=<><Navbar mode="solid"/><main className="bg-cream pt-28"><MenuPresentation categories={categories} items={items}/></main><Footer/></>;}else{const rows=await attach([selected]);const variants={promos:"promo",events:"event",gallery:"gallery"} as const;content=<CollectionPage eyebrow="Authenticated preview" title={config.title} description="Draft preview. This content is not publicly available." emptyMessage="Preview unavailable." records={rows} variant={variants[module as keyof typeof variants]}/>}
return <><div className="fixed inset-x-0 top-0 z-[60] bg-gold px-4 py-2 text-center text-xs font-bold tracking-wide text-dark-green uppercase">Secure CMS preview · {revision?"historical revision":"current draft"}</div><div className="pt-8">{content}</div></>}
function PreviewError({children}:{children:ReactNode}){return <main className="grid min-h-screen place-items-center bg-cream p-6"><p role="alert" className="rounded-lg border border-gold/40 bg-white p-8">{children}</p></main>}
