export type OsModuleKey = "projects" | "tasks" | "campaigns" | "content" | "reports" | "team" | "knowledge" | "roadmap";
export type OsField = { name: string; label: string; kind: "text" | "textarea" | "number" | "date" | "datetime-local" | "select" | "relation" | "relations" | "media" | "tags" | "checkbox"; required?: boolean; options?: readonly string[]; relation?: "projects" | "tasks" | "campaigns" | "profiles" | "media" };
export type OsModuleConfig = { key: OsModuleKey; table: string; title: string; description: string; titleField: string; fields: readonly OsField[]; superAdminOnly?: boolean };

const priority = ["low", "medium", "high", "urgent"] as const;
export const osModules: Record<OsModuleKey, OsModuleConfig> = {
  projects: { key: "projects", table: "os_projects", title: "Projects", description: "Kelola inisiatif bisnis dari perencanaan hingga selesai.", titleField: "name", fields: [
    { name: "name", label: "Project name", kind: "text", required: true }, { name: "objective", label: "Objective", kind: "textarea" }, { name: "description", label: "Description", kind: "textarea" }, { name: "owner_id", label: "Owner", kind: "relation", relation: "profiles" }, { name: "team", label: "Team", kind: "relations", relation: "profiles" }, { name: "priority", label: "Priority", kind: "select", options: priority, required: true }, { name: "start_date", label: "Start date", kind: "date" }, { name: "deadline", label: "Deadline", kind: "date" }, { name: "status", label: "Status", kind: "select", options: ["planning","active","review","completed","cancelled"], required: true }, { name: "tags", label: "Tags", kind: "tags" }, { name: "notes", label: "Notes", kind: "textarea" },
  ] },
  tasks: { key: "tasks", table: "os_tasks", title: "Tasks", description: "Kelola task dan subtask yang terhubung ke project.", titleField: "title", fields: [
    { name: "title", label: "Title", kind: "text", required: true }, { name: "description", label: "Description", kind: "textarea" }, { name: "project_id", label: "Project", kind: "relation", relation: "projects" }, { name: "parent_task_id", label: "Parent task (creates a subtask)", kind: "relation", relation: "tasks" }, { name: "assigned_to", label: "Assigned to", kind: "relation", relation: "profiles" }, { name: "priority", label: "Priority", kind: "select", options: priority, required: true }, { name: "deadline", label: "Deadline", kind: "date" }, { name: "status", label: "Status", kind: "select", options: ["todo","in_progress","review","completed","cancelled"], required: true }, { name: "attachment_media_id", label: "Attachment", kind: "media", relation: "media" }, { name: "notes", label: "Notes", kind: "textarea" },
  ] },
  campaigns: { key: "campaigns", table: "os_campaigns", title: "Campaigns", description: "Rencanakan dan evaluasi campaign marketing dengan data nyata.", titleField: "campaign_name", fields: [
    { name: "campaign_name", label: "Campaign name", kind: "text", required: true }, { name: "objective", label: "Objective", kind: "textarea" }, { name: "target_audience", label: "Target audience", kind: "textarea" }, { name: "offer", label: "Offer", kind: "textarea" }, { name: "channels", label: "Channels", kind: "tags" }, { name: "budget", label: "Budget", kind: "number" }, { name: "start_date", label: "Start date", kind: "date" }, { name: "end_date", label: "End date", kind: "date" }, { name: "owner_id", label: "Owner", kind: "relation", relation: "profiles" }, { name: "status", label: "Status", kind: "select", options: ["idea","planning","preparation","execution","monitoring","evaluation","completed","cancelled"], required: true }, { name: "expected_result", label: "Expected result", kind: "textarea" }, { name: "notes", label: "Notes", kind: "textarea" },
  ] },
  content: { key: "content", table: "os_content_items", title: "Content", description: "Kelola alur ide, brief, review, approval, dan publikasi.", titleField: "title", fields: [
    { name: "title", label: "Title", kind: "text", required: true }, { name: "content_type", label: "Content type", kind: "select", options: ["instagram_post","instagram_story","reels","website","promo","event","campaign_asset"], required: true }, { name: "campaign_id", label: "Campaign", kind: "relation", relation: "campaigns" }, { name: "owner_id", label: "Owner", kind: "relation", relation: "profiles" }, { name: "brief", label: "Brief", kind: "textarea" }, { name: "publish_at", label: "Publish at", kind: "datetime-local" }, { name: "status", label: "Status", kind: "select", options: ["idea","brief","draft","review","approved","published","cancelled"], required: true }, { name: "attachment_media_id", label: "Attachment", kind: "media", relation: "media" }, { name: "notes", label: "Notes", kind: "textarea" },
  ] },
  reports: { key: "reports", table: "os_reports", title: "Reports", description: "Dokumentasikan laporan berbasis project dan campaign aktual.", titleField: "title", fields: [
    { name: "title", label: "Title", kind: "text", required: true }, { name: "report_type", label: "Report type", kind: "select", options: ["project","campaign","content","event","operational","management_summary"], required: true }, { name: "project_id", label: "Project", kind: "relation", relation: "projects" }, { name: "campaign_id", label: "Campaign", kind: "relation", relation: "campaigns" }, { name: "narrative", label: "Narrative", kind: "textarea" }, { name: "status", label: "Status", kind: "select", options: ["draft","published","archived"], required: true }, { name: "attachment_media_id", label: "Attachment", kind: "media", relation: "media" },
  ] },
  knowledge: { key: "knowledge", table: "os_knowledge_articles", title: "Knowledge", description: "Simpan SOP, panduan, materi training, dan pengetahuan internal.", titleField: "title", fields: [
    { name: "title", label: "Title", kind: "text", required: true }, { name: "content_type", label: "Content type", kind: "select", options: ["sop","brand_guidelines","marketing_guidelines","operational_notes","training_material","internal_faq"], required: true }, { name: "body", label: "Body", kind: "textarea" }, { name: "status", label: "Status", kind: "select", options: ["draft","published","archived"], required: true }, { name: "attachment_media_id", label: "Attachment", kind: "media", relation: "media" },
  ] },
  roadmap: { key: "roadmap", table: "os_roadmap_items", title: "Roadmap", description: "Susun prioritas strategis Now, Next, dan Later.", titleField: "title", fields: [
    { name: "title", label: "Title", kind: "text", required: true }, { name: "description", label: "Description", kind: "textarea" }, { name: "horizon", label: "Horizon", kind: "select", options: ["now","next","later"], required: true }, { name: "display_order", label: "Display order", kind: "number", required: true }, { name: "active", label: "Active", kind: "checkbox" },
  ] },
  team: { key: "team", table: "os_team_responsibilities", title: "Team", description: "Kelola tanggung jawab pengguna internal yang telah disetujui.", titleField: "responsibility", superAdminOnly: true, fields: [
    { name: "user_id", label: "User", kind: "relation", relation: "profiles", required: true }, { name: "role", label: "Role", kind: "select", options: ["viewer","content_manager","reservation_staff","super_admin"], required: true }, { name: "responsibility", label: "Responsibility", kind: "textarea", required: true }, { name: "active", label: "Active", kind: "checkbox" },
  ] },
};

export function isOsModule(value: string): value is OsModuleKey { return Object.hasOwn(osModules, value); }
